### ISSUE TITLE
vNext

### ISSUE THREAD

**Issue by veccsolutions** [autofac/Autofac.Multitenant#2]
The MultiTenant nuget package is not working with vNext projects due to issues with using HashTables, HttpContext and the ServiceProvider from the Autofac Dependency Injection package.

I was able to get it to work by changing a few things.
1. Convert to vnext project.
2. Add the Microsoft.AspNet.Http and Microsoft.AspNet.Http.Abstrations dependencies
2. Modify RequestParameterTenantIdentificationStrategy to use IHttpContextAccessor for non .NET45 targeted projects.
3. Changed MultitenantContainer to use ConcurrentDictionary<object, object> instead of HashTable

I then had to build my own service provider, copied from Autofac.Framework.DependencyInjection. The reason I needed to do that is the need to create the new provider with the multi tenant context.

In startup.cs, I was now able to do this and it worked correctly:

            var identificationStrategy = new MultiTenantIdentificationStrategy();
            var containerBuilder = new ContainerBuilder();
            containerBuilder.Populate(services);
            containerBuilder.RegisterType<TestClassDefault>().As<ITestClass>().InstancePerLifetimeScope(); //set a default

            var container = containerBuilder.Build();
            var multiTenantContainer = new Autofac.Extras.Multitenant.MultitenantContainer(identificationStrategy, container);
            
            //setup tenants
            multiTenantContainer.ConfigureTenant("1",
                builder =>
                {
                    builder.RegisterType<TestClass1>().As<ITestClass>().InstancePerLifetimeScope();
                });

            multiTenantContainer.ConfigureTenant("2",
                builder =>
                {
                    builder.RegisterType<TestClass2>().As<ITestClass>().InstancePerLifetimeScope();
                });

            //update types
            containerBuilder = new ContainerBuilder();
            containerBuilder.RegisterType<AutoServiceProvider>().As<IServiceProvider>().SingleInstance(); //set the service provider to the correct service provider
            containerBuilder.RegisterInstance(multiTenantContainer).As<IComponentContext>().SingleInstance(); //set the component context to the multitenant container
            containerBuilder.Update(multiTenantContainer); //update the container with the new types

            return multiTenantContainer.Resolve<IServiceProvider>();

I have code done, I could do a pull request for it.

**Comment by tillig** [comment]
Nothing has been ported to vNext or tested other than the configuration package. The builds of vNext haven't really been stable until recently. I'm surprised you got the Autofac 4.0.0 beta to correctly be added alongside Autofac.Multitenant. I thought we had it marked incompatible.

Regardless, we're working on it. Thanks!
