### ISSUE TITLE
Autofac Multitenancy does not add tenant configuration when using new JSON config

### ISSUE THREAD

**Issue by beachwalker** [autofac/Autofac.Multitenant#4]
The Multitenant module does not apply the configuration to the builder anymore.

If you have a the (nonmultitenant) core container build up and apply the configuration
to the new MultitentantContainer the new container should add its additional configuration to the already build configuration (e.g. add new additonal T specific for customer, when resolving IEnumerable<T>)

(this is the multitenant part of my bootstrapping)

```csharp
// Create the Container for IoC
this.container = builder.Build();

// Todo: Use same principle as used for tenants also for different application types/profiles
ITenantIdentificationStrategy tenantIdentificationStrategy;

// check if whe should go single- or multitenancy
if (this.container.TryResolve(out tenantIdentificationStrategy))
{
	var multitenantContainer =
		new MultitenantContainer(
			tenantIdentificationStrategy,
			this.container);
	
	var tenantsConfigdirectory = new DirectoryInfo(configDirectory.FullName + Path.DirectorySeparatorChar + this.configForTenants);

	RegisterMultitenantModules(multitenantContainer, tenantsConfigdirectory)
		.OnSuccess(() =>
				{
					Log.Info(
						logm => logm("Using multi-tenant container."));
					// use multitenant container
					this.container = multitenantContainer;
				});
}
else
{
	Log.Info(logm => logm("Using single-tenant container."));
}
```

The registration of Multitenant parts is fairly simple:

```csharp
foreach (var tenant in directory.GetDirectories())
{
	try
	{
		multitenantContainer.ConfigureTenant(
			tenant.Name,
			builder =>
			{
				var tenantDirectory = new DirectoryInfo(directory.FullName + Path.DirectorySeparatorChar + tenant);

				var config = new ConfigurationBuilder();

				try
				{
					foreach (var file in tenantDirectory.GetFiles("*.json"))
					{
						config.AddJsonFile(file.FullName);
					}

					foreach (var file in tenantDirectory.GetFiles("*.xml"))
					{
						config.AddXmlFile(file.FullName);
					}
				}
				catch (DirectoryNotFoundException exception)
				{
					Log.Warn(logm => logm("Directory for tenant '{0}' not found.", tenant), exception);
				}

				// Register this module for json/xml configuration as last module to allow (emergency) overrides.
				builder.RegisterModule(new ConfigurationModule(config.Build()));
			});

		return Result.Ok();
	}
	catch (ConfigurationErrorsException exception)
	{
		const string Message = "Configuration errors during trying to read the tenant configuration for {0}.";

		Log.Error(logm => logm(Message, tenant), exception);

		return Result.Fail(string.Format(Message, tenant));
	}
}
```
The debugger steps through the process and all seems to be working (reading tenant config etc.) but the new config is not applied.

**Comment by tillig** [comment]
Unfortunately, I'm unable to reproduce the problem you're seeing. I've attached a small console app repro showing multitenant containers correctly working with JSON-based configuration.

[MultitenantConfigRepro.zip](https://github.com/autofac/Autofac.Multitenant/files/115996/MultitenantConfigRepro.zip)

Given I can't repro the issue, what I'd suggest is to see if you can simplify your logic and see if you can get things to work in your solution as well, then add complexity back until you see things start to fail.

If you are able to provide a _simple, self-contained repro_ showing that it's not working, I'd be happy to reopen and look into it further.

**Comment by beachwalker** [comment]
Your sample worked for me, too. Thanks for your effort trying to find a bug (which seems to be in my code now). The difference in the environment is that I'm still using 4.5.1 and your sample is 4.5.2. However, I try to find the problem in my code and put the solution here (in case anyone else is interested how this happened).
