### ISSUE TITLE
Getting all registered tenants Ids and clearing registrations

### ISSUE THREAD

**Issue by gtrubach** [autofac/Autofac.Multitenant#9]
Now we have a feature for reconfiguring tenants.  It's a really cool feature!

But for full tenants control I suggest to add two methods:
1. Getting all configured tenant Ids. This will help with not storing Ids in application memory, because we already have it in Multitenant dictionary.
2. Clearing all registrations. We can now remove them one-by-one. But in some cases it's necessary to remove all.

What do you think about it?

**Comment by tillig** [comment]
That all sounds totally reasonable.

**Comment by tillig** [comment]
This will be released as part of 4.2.0.
